// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSXQkZfIb6zRB8EUgtipnMt24khRmKfEU',
    appId: '1:956115191240:web:7e92f245679f3ae6416cfd',
    messagingSenderId: '956115191240',
    projectId: 'tech-store-cd52b',
    authDomain: 'tech-store-cd52b.firebaseapp.com',
    storageBucket: 'tech-store-cd52b.firebasestorage.app',
    measurementId: 'G-VGTX345728',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvsA7SS6cJrIFkAvoQYlZX3iJSEPr6Rvg',
    appId: '1:956115191240:android:e77ef47818a32f61416cfd',
    messagingSenderId: '956115191240',
    projectId: 'tech-store-cd52b',
    storageBucket: 'tech-store-cd52b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3O9o1mBug0B-c4HbWAHqQ-AHYCAw-zA4',
    appId: '1:956115191240:ios:95701d71bf7b9b74416cfd',
    messagingSenderId: '956115191240',
    projectId: 'tech-store-cd52b',
    storageBucket: 'tech-store-cd52b.firebasestorage.app',
    iosBundleId: 'com.example.techStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3O9o1mBug0B-c4HbWAHqQ-AHYCAw-zA4',
    appId: '1:956115191240:ios:95701d71bf7b9b74416cfd',
    messagingSenderId: '956115191240',
    projectId: 'tech-store-cd52b',
    storageBucket: 'tech-store-cd52b.firebasestorage.app',
    iosBundleId: 'com.example.techStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSXQkZfIb6zRB8EUgtipnMt24khRmKfEU',
    appId: '1:956115191240:web:b47139f8fb2ed39e416cfd',
    messagingSenderId: '956115191240',
    projectId: 'tech-store-cd52b',
    authDomain: 'tech-store-cd52b.firebaseapp.com',
    storageBucket: 'tech-store-cd52b.firebasestorage.app',
    measurementId: 'G-H6V4FQKF19',
  );
}